name: Test Debug (GCC)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build the Docker image from the GCC Dockerfile
      - name: Build Docker Image
        run: docker build -f Dockerfile.gcc -t gcc-image:latest .

      # Run the tests inside the Docker container
      - name: Run Tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/mnt/build \
            -w /mnt/build -u $(id -u):$(id -g) gcc-image:latest \
            bash -c "make debug && cd build/debug && ctest --output-on-failure"
